import sys
import os
sureHome	= os.environ['SURE_HOME']
sys.path.insert(0, sureHome)

#print('')
#print('')
#print('')
#print('')
#print('                   ./oo/.                ')
#print('               `-+hmmmmmdh+-             ')
#print('            .:sdmmmmmmmmmmmmds:`         ')
#print('         -+ydmmmmmmmmmmmmmmmmmmdy+-      ')
#print('     `:ohmmmmmmmmmmmhyyhmmmmmmmmmmmho:`  ')
#print('    .ymmmmmmmmmmmmms`  `smmmmmmmmmmmmmy. ')
#print('   :dyosymmmmmmmmmmmdhhdmmmmmmmmmmmyssyd:')
#print('   /mmmdhssyhmmmmmmmmmmmmmmmmmmdysshdmmm/')
#print('   /mmy+ymmdysshmmmmmmmmmmmmhysydmmmmmmm/')
#print('   /mm/  +mmmmdhssydmmmmdysshdmmmmmmmmmm/     Powered by SURE')
#print('   /mmd+-:mmmmmmhddyo++sydmmmmmmmmmmmmmm/')
#print('   /mmmmmmmmmmm+`.ymmoommh/.ommmmmmmmmmm/')
#print('   /mmmmmmm+ohmh. `mmyymm. `ymho+mmmmmmm/')
#print('   +mmmdmmd` `hmdyymmyymmoohmh` `dmdydmm+')
#print('   +mm/.:hmy:-ymmmmmmyymmmmmmy-:hms. :mm+')
#print('   /mms` .mmmmmmmmmmmyymmmmmmmmmmm-`-hmm/')
#print('   `+hddsymmmmmy/smmmyymmmmmmmmmmmdhmdh+`')
#print('     `./ydmmmmmo  :mmyymmmmmmmmmmmdy/.`  ')
#print('         .:ohmmmo-:mmsymmmmmmmmho:.      ')
#print('            `-+ydmmmmssmmmmdy/-`         ')
#print('                .:shmssmho:.             ')
#print('                   `-..-`                ')
#print('')
#print('')
#print('')
#print('')
